import type { Metadata } from 'next';
import { fontMono, fontSans, fontSerif } from '@/config/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${fontSerif.variable} ${fontSans.variable}
          ${fontMono.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
