import type { Metadata } from 'next';
import { fontMono, fontSans, fontSerif } from '@/config/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        {/* todo: esto es temporal, tengo, antes que arreglen el paquete npm */}
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css"
        />
      </head>
      <body
        className={`${fontSerif.variable} ${fontSans.variable}
          ${fontMono.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
